#!/bin/bash

currentDir=`pwd`

if [ -d "repo/$1.git" ]; then
    echo "repository is exists"
    exit
else 
    mkdir repo/$1.git
fi

mkdir $2/$1

pushd repo/$1.git

git init --bare
git config core.bare false
git config core.worktree $2/$1
git config receive.denyCurrentBranch ignore

cp $currentDir/post-receive $currentDir/repo/$1.git/hooks/post-receive

sudo chmod a+x $currentDir/repo/$1.git/hooks/post-receive
popd

echo 'The git repository is created.'
echo 'done'
