#!/bin/bash

mkdir ~/repo/$1.git

mkdir $2

pushd ~/repo/$1.git

git init --bare
git config core.bare false
git config core.worktree $2
git config receive.denyCurrentBranch ignore

cp post-receive ~/repo/$1.git/hooks/post-receive

sudo chmod a+x ~/repo/$1.git/hooks/post-receive
popd

echo 'done'
